# <center> Assignment #1 
## <center>  Exploratory data analysis with Pandas

We will be doing EDA on Adult dataset having following attributes:
- `age`: continuous.
- `workclass`: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- `fnlwgt`: continuous.
- `education`: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- `education-num`: continuous.
- `marital-status`: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- `occupation`: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- `relationship`: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- `race`: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- `sex`: Female, Male.
- `capital-gain`: continuous.
- `capital-loss`: continuous.
- `hours-per-week`: continuous.
- `native-country`: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- `salary`: >50K,<=50K

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [2]:
df = pd.read_csv('adult.data.csv')

In [3]:
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

**1. How many men and women (*sex* feature) are represented in this dataset?**

In [122]:
df['sex'].value_counts()

Male      21790
Female    10771
Name: sex, dtype: int64

**2. What is the average age (*age* feature) of women?**

In [128]:
women_age = df['age'][df['sex'] == 'Female']
women_age.mean()

36.85823043357163

In [132]:
df.loc[df['sex'] == 'Female', 'age'].mean()

36.85823043357163

**3. What is the percentage of German citizens (*native-country* feature)?**

In [141]:
total_count = df['native-country'].shape[0]
Germany_count = (df['native-country'] == 'Germany').sum()
German_percentage = (Germany_count/total_count)*100
German_percentage

0.42074874850281013

**4-5. What are the mean and standard deviation of age for those who earn more than 50K per year (*salary* feature) and those who earn less than 50K per year? **

In [155]:
more = df.loc[df['salary']=='>50K', 'age']
less = df.loc[df['salary']=='<=50K', 'age']

print("more salary: mean {0} & std {1} | less salary: mean {2} & std {3}".format(more.mean(), more.std(), less.mean(), less.std()))

more salary: mean 44.24984058155847 & std 10.51902771985177 | less salary: mean 36.78373786407767 & std 14.020088490824813

**6. Is it true that people who earn more than 50K have at least high school education? (*education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* or *Doctorate* feature)**

### No, it's not true. We have people earning >50K and still have education of 11th and even 9th grade.

In [145]:
df.loc[df['salary'] == '>50K', 'education'].unique()

array(['HS-grad', 'Masters', 'Bachelors', 'Some-college', 'Assoc-voc',
       'Doctorate', 'Prof-school', 'Assoc-acdm', '7th-8th', '12th',
       '10th', '11th', '9th', '5th-6th', '1st-4th'], dtype=object)

In [148]:
df.loc[df['salary'] == '>50K'][df['education'] == '11th']

/Users/punchh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
729,65,Self-emp-not-inc,118474,11th,7,Married-civ-spouse,Exec-managerial,Husband,White,Male,9386,0,59,?,>50K
934,37,Private,186934,11th,7,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,44,United-States,>50K
1495,28,Self-emp-inc,210295,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,>50K
1496,32,Private,80058,11th,7,Divorced,Sales,Not-in-family,White,Male,0,0,43,United-States,>50K
1978,48,Self-emp-not-inc,104790,11th,7,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,>50K
2190,50,Private,156877,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,70,United-States,>50K
2332,23,Self-emp-not-inc,282604,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,7688,0,60,United-States,>50K
2986,64,Local-gov,244903,11th,7,Married-civ-spouse,Craft-repair,Husband,Black,Male,0,0,40,United-States,>50K
3290,33,Private,83446,11th,7,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,>50K
4491,60,Private,121832,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,>50K
4555,41,Private,67339,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,7688,0,40,United-States,>50K
4807,42,Local-gov,195124,11th,7,Divorced,Sales,Unmarried,White,Male,7430,0,50,Puerto-Rico,>50K
4880,37,Private,30267,11th,7,Never-married,Transport-moving,Not-in-family,White,Male,0,0,60,United-States,>50K
8633,23,Private,106957,11th,7,Never-married,Craft-repair,Own-child,Asian-Pac-Islander,Male,14344,0,40,Vietnam,>50K
10465,63,Private,180911,11th,7,Married-civ-spouse,Protective-serv,Husband,White,Male,4386,0,37,United-States,>50K
11155,26,Private,248990,11th,7,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,>50K
11170,44,Private,300528,11th,7,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,>50K
11292,51,Private,29580,11th,7,Married-civ-spouse,Sales,Husband,White,Male,4386,0,30,United-States,>50K
11685,51,Private,43354,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
12241,28,Private,410216,11th,7,Married-civ-spouse,Craft-repair,Not-in-family,White,Male,0,0,60,United-States,>50K
13335,38,Private,76878,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,5178,0,40,United-States,>50K
13480,44,Private,175641,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,>50K
14265,47,Private,274200,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,7298,0,40,United-States,>50K
14279,22,Private,231053,11th,7,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,70,United-States,>50K
14888,36,Private,201769,11th,7,Never-married,Protective-serv,Not-in-family,Black,Male,13550,0,40,United-States,>50K
15133,46,Private,241935,11th,7,Married-civ-spouse,Other-service,Husband,Black,Male,7688,0,40,United-States,>50K
15567,61,State-gov,159908,11th,7,Widowed,Other-service,Unmarried,White,Female,0,0,32,United-States,>50K
15710,30,Self-emp-not-inc,455995,11th,7,Never-married,Craft-repair,Not-in-family,White,Male,0,0,45,United-States,>50K
15839,25,Private,120238,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,5178,0,40,Poland,>50K
16847,32,Private,95885,11th,7,Never-married,Craft-repair,Not-in-family,Amer-Indian-Eskimo,Male,13550,0,60,United-States,>50K
17206,44,Private,175669,11th,7,Married-civ-spouse,Prof-specialty,Wife,White,Female,5178,0,36,United-States,>50K
17264,38,Self-emp-not-inc,43712,11th,7,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,1887,45,United-States,>50K
18309,27,Private,160786,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,1902,40,United-States,>50K
18321,51,Self-emp-not-inc,127149,11th,7,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,45,United-States,>50K
18393,54,Private,235693,11th,7,Divorced,Adm-clerical,Not-in-family,White,Male,0,0,40,United-States,>50K
18715,28,Private,105817,11th,7,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
18777,54,Private,225307,11th,7,Divorced,Craft-repair,Own-child,White,Female,0,0,50,United-States,>50K
18910,41,Private,428499,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,1485,50,United-States,>50K
19140,45,Private,172822,11th,7,Divorced,Transport-moving,Not-in-family,White,Male,0,2824,76,United-States,>50K
19923,28,Private,183151,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,7688,0,40,United-States,>50K
20251,52,Private,138944,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
20277,48,Private,195437,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,>50K
20379,61,Private,72442,11th,7,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,United-States,>50K
21408,60,Self-emp-inc,90915,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,>50K
21475,56,Self-emp-not-inc,62539,11th,7,Widowed,Other-service,Unmarried,White,Female,0,0,65,Greece,>50K
22428,46,Private,155659,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,1902,40,United-States,>50K
22947,37,Private,219141,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,7688,0,40,United-States,>50K
23417,50,Private,197322,11th,7,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
23973,37,Private,112271,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K
24148,46,Private,185291,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,45,United-States,>50K
24933,65,Self-emp-inc,66360,11th,7,Married-civ-spouse,Exec-managerial,Husband,White,Male,6418,0,35,United-States,>50K
25250,36,Private,186035,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,5178,0,40,United-States,>50K
25940,24,Private,235071,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,>50K
26369,46,Private,100067,11th,7,Married-civ-spouse,Other-service,Wife,Black,Female,0,0,35,United-States,>50K
27780,38,Private,287701,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,48,United-States,>50K
28908,46,Private,176552,11th,7,Divorced,Prof-specialty,Unmarried,Amer-Indian-Eskimo,Male,0,0,40,United-States,>50K
30234,58,Federal-gov,72998,11th,7,Divorced,Craft-repair,Not-in-family,Black,Female,14084,0,40,United-States,>50K
30701,53,Private,183973,11th,7,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,48,United-States,>50K
30936,54,Private,154949,11th,7,Married-civ-spouse,Other-service,Wife,Black,Female,0,0,40,United-States,>50K
32138,50,Self-emp-inc,121441,11th,7,Never-married,Exec-managerial,Other-relative,White,Male,0,2444,40,United-States,>50K

**7. Display age statistics for each race (*race* feature) and each gender (*sex* feature). Use *groupby()* and *describe()*. Find the maximum age of men of *Amer-Indian-Eskimo* race.**

In [159]:
for (race), df_sub in df.groupby(['race']):
    for (sex), df_sub in df.groupby(['sex']):
        print('race: {0} | sex: {1}'.format(race, sex))
        print(df_sub['age'].describe())

race: Amer-Indian-Eskimo | sex: Female
count    10771.000000
mean        36.858230
std         14.013697
min         17.000000
25%         25.000000
50%         35.000000
75%         46.000000
max         90.000000
Name: age, dtype: float64
race: Amer-Indian-Eskimo | sex: Male
count    21790.000000
mean        39.433547
std         13.370630
min         17.000000
25%         29.000000
50%         38.000000
75%         48.000000
max         90.000000
Name: age, dtype: float64
race: Asian-Pac-Islander | sex: Female
count    10771.000000
mean        36.858230
std         14.013697
min         17.000000
25%         25.000000
50%         35.000000
75%         46.000000
max         90.000000
Name: age, dtype: float64
race: Asian-Pac-Islander | sex: Male
count    21790.000000
mean        39.433547
std         13.370630
min         17.000000
25%         29.000000
50%         38.000000
75%         48.000000
max         90.000000
Name: age, dtype: float64
race: Black | sex: Female
count    10771.000000
mean        36.858230
std         14.013697
min         17.000000
25%         25.000000
50%         35.000000
75%         46.000000
max         90.000000
Name: age, dtype: float64
race: Black | sex: Male
count    21790.000000
mean        39.433547
std         13.370630
min         17.000000
25%         29.000000
50%         38.000000
75%         48.000000
max         90.000000
Name: age, dtype: float64
race: Other | sex: Female
count    10771.000000
mean        36.858230
std         14.013697
min         17.000000
25%         25.000000
50%         35.000000
75%         46.000000
max         90.000000
Name: age, dtype: float64
race: Other | sex: Male
count    21790.000000
mean        39.433547
std         13.370630
min         17.000000
25%         29.000000
50%         38.000000
75%         48.000000
max         90.000000
Name: age, dtype: float64
race: White | sex: Female
count    10771.000000
mean        36.858230
std         14.013697
min         17.000000
25%         25.000000
50%         35.000000
75%         46.000000
max         90.000000
Name: age, dtype: float64
race: White | sex: Male
count    21790.000000
mean        39.433547
std         13.370630
min         17.000000
25%         29.000000
50%         38.000000
75%         48.000000
max         90.000000
Name: age, dtype: float64

**8. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men (*marital-status* feature)? Consider as married those who have a *marital-status* starting with *Married* (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.**

In [173]:
df.loc[(df['sex']=='Male') & (df['marital-status'].str.startswith("Married")), 'salary'].value_counts()

df.loc[(df['sex'] == 'Male') & (df['marital-status'].isin(['Never-married', 'Separated',
                                                                'Divorced', 'Widowed'])), 'salary'].value_counts()

<=50K    7552
>50K      697
Name: salary, dtype: int64

**9. What is the maximum number of hours a person works per week (*hours-per-week* feature)? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?**

In [170]:
max_hrs = df['hours-per-week'].max()
print('max num hrs: {0}'.format(max_hrs))

workaholics = df[df['hours-per-week'] == max_hrs].shape[0]
print('total workers: {0}'.format(workaholics))

rich = float(df[(df['hours-per-week'] == max_hrs) & (df['salary'] == '>50K')].shape[0]) / workaholics
print('percentage: {0}'.format(int(100*rich)))

max num hrs: 99
total workers: 85
percentage: 29

**10. Count the average time of work (*hours-per-week*) for those who earn a little and a lot (*salary*) for each country (*native-country*). What will these be for Japan?**

In [172]:
for (country, salary), df_sub in df.groupby(['native-country', 'salary']):
    print(country, salary, round(df_sub['hours-per-week'].mean(),1))

? <=50K 40.2
? >50K 45.5
Cambodia <=50K 41.4
Cambodia >50K 40.0
Canada <=50K 37.9
Canada >50K 45.6
China <=50K 37.4
China >50K 38.9
Columbia <=50K 38.7
Columbia >50K 50.0
Cuba <=50K 38.0
Cuba >50K 42.4
Dominican-Republic <=50K 42.3
Dominican-Republic >50K 47.0
Ecuador <=50K 38.0
Ecuador >50K 48.8
El-Salvador <=50K 36.0
El-Salvador >50K 45.0
England <=50K 40.5
England >50K 44.5
France <=50K 41.1
France >50K 50.8
Germany <=50K 39.1
Germany >50K 45.0
Greece <=50K 41.8
Greece >50K 50.6
Guatemala <=50K 39.4
Guatemala >50K 36.7
Haiti <=50K 36.3
Haiti >50K 42.8
Holand-Netherlands <=50K 40.0
Honduras <=50K 34.3
Honduras >50K 60.0
Hong <=50K 39.1
Hong >50K 45.0
Hungary <=50K 31.3
Hungary >50K 50.0
India <=50K 38.2
India >50K 46.5
Iran <=50K 41.4
Iran >50K 47.5
Ireland <=50K 40.9
Ireland >50K 48.0
Italy <=50K 39.6
Italy >50K 45.4
Jamaica <=50K 38.2
Jamaica >50K 41.1
Japan <=50K 41.0
Japan >50K 48.0
Laos <=50K 40.4
Laos >50K 40.0
Mexico <=50K 40.0
Mexico >50K 46.6
Nicaragua <=50K 36.1
Nicaragua >50K 37.5
Outlying-US(Guam-USVI-etc) <=50K 41.9
Peru <=50K 35.1
Peru >50K 40.0
Philippines <=50K 38.1
Philippines >50K 43.0
Poland <=50K 38.2
Poland >50K 39.0
Portugal <=50K 41.9
Portugal >50K 41.5
Puerto-Rico <=50K 38.5
Puerto-Rico >50K 39.4
Scotland <=50K 39.4
Scotland >50K 46.7
South <=50K 40.2
South >50K 51.4
Taiwan <=50K 33.8
Taiwan >50K 46.8
Thailand <=50K 42.9
Thailand >50K 58.3
Trinadad&Tobago <=50K 37.1
Trinadad&Tobago >50K 40.0
United-States <=50K 38.8
United-States >50K 45.5
Vietnam <=50K 37.2
Vietnam >50K 39.2
Yugoslavia <=50K 41.6
Yugoslavia >50K 49.5